### ISSUE TITLE
Help url is incorrect

### ISSUE THREAD

**Issue by t3kt** [mickeyvanolst/TD-chainGpu-Physics-Sim-Tool#1]
https://github.com/mickeyvanolst/TD-Chain-Physics-Sim-Tool

instead of

https://github.com/mickeyvanolst/TD-chainGpu-Physics-Sim-Tool

**Comment by mickeyvanolst** [comment]
very relieved to have this as my first issue log :-)

**Comment by t3kt** [comment]
yeah a nice easy one. 😄
